-include .config
export

.PHONY: modules
modules:
	@$(MAKE) -C $(KERNEL_SRC) M=$(BACKPORT_DIR) EXTRA_CFLAGS="-Wno-error=int-conversion" modules

.PHONY: clean
clean:
	@$(MAKE) -C $(KERNEL_SRC) M=$(BACKPORT_DIR) clean
